version: '3.7'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db:db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    restart: always
    container_name: db
    ports:
      -5433:5432
    environment:
      - POSTGRES_DB: file_db
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres